// This file will be auto-generated by `npx supabase gen types typescript`
// For now, define the shape manually to unblock development.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string;
          phone: string | null;
          avatar_url: string | null;
          role: "client" | "provider" | null;
          bio: string | null;
          experience_years: number | null;
          avg_rating: number;
          total_reviews: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name: string;
          phone?: string | null;
          avatar_url?: string | null;
          role?: "client" | "provider" | null;
          bio?: string | null;
          experience_years?: number | null;
          is_active?: boolean;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string;
          phone?: string | null;
          avatar_url?: string | null;
          role?: "client" | "provider" | null;
          bio?: string | null;
          experience_years?: number | null;
          is_active?: boolean;
        };
        Relationships: [];
      };
      categories: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          icon: string;
          color: string;
          sort_order: number;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          icon: string;
          color?: string;
          sort_order?: number;
          is_active?: boolean;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          icon?: string;
          color?: string;
          sort_order?: number;
          is_active?: boolean;
        };
        Relationships: [];
      };
      services: {
        Row: {
          id: string;
          category_id: string;
          name: string;
          description: string | null;
          base_price: number;
          icon: string;
          sort_order: number;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          category_id: string;
          name: string;
          description?: string | null;
          base_price: number;
          icon?: string;
          sort_order?: number;
          is_active?: boolean;
        };
        Update: {
          id?: string;
          category_id?: string;
          name?: string;
          description?: string | null;
          base_price?: number;
          icon?: string;
          sort_order?: number;
          is_active?: boolean;
        };
        Relationships: [
          {
            foreignKeyName: "services_category_id_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["id"];
          },
        ];
      };
      service_variables: {
        Row: {
          id: string;
          service_id: string;
          name: string;
          label: string;
          type: "number" | "select" | "boolean";
          options: Json | null;
          min_value: number | null;
          max_value: number | null;
          default_value: string | null;
          price_modifier: number;
          sort_order: number;
        };
        Insert: {
          id?: string;
          service_id: string;
          name: string;
          label: string;
          type?: "number" | "select" | "boolean";
          options?: Json | null;
          min_value?: number | null;
          max_value?: number | null;
          default_value?: string | null;
          price_modifier?: number;
          sort_order?: number;
        };
        Update: {
          id?: string;
          service_id?: string;
          name?: string;
          label?: string;
          type?: "number" | "select" | "boolean";
          options?: Json | null;
          min_value?: number | null;
          max_value?: number | null;
          default_value?: string | null;
          price_modifier?: number;
          sort_order?: number;
        };
        Relationships: [
          {
            foreignKeyName: "service_variables_service_id_fkey";
            columns: ["service_id"];
            isOneToOne: false;
            referencedRelation: "services";
            referencedColumns: ["id"];
          },
        ];
      };
      provider_services: {
        Row: {
          id: string;
          provider_id: string;
          service_id: string;
          base_price: number;
          immediate_available: boolean;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          provider_id: string;
          service_id: string;
          base_price: number;
          immediate_available?: boolean;
          is_active?: boolean;
        };
        Update: {
          id?: string;
          provider_id?: string;
          service_id?: string;
          base_price?: number;
          immediate_available?: boolean;
          is_active?: boolean;
        };
        Relationships: [
          {
            foreignKeyName: "provider_services_provider_id_fkey";
            columns: ["provider_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "provider_services_service_id_fkey";
            columns: ["service_id"];
            isOneToOne: false;
            referencedRelation: "services";
            referencedColumns: ["id"];
          },
        ];
      };
      provider_availability: {
        Row: {
          id: string;
          provider_id: string;
          day_of_week: number;
          start_time: string;
          end_time: string;
        };
        Insert: {
          id?: string;
          provider_id: string;
          day_of_week: number;
          start_time: string;
          end_time: string;
        };
        Update: {
          id?: string;
          provider_id?: string;
          day_of_week?: number;
          start_time?: string;
          end_time?: string;
        };
        Relationships: [
          {
            foreignKeyName: "provider_availability_provider_id_fkey";
            columns: ["provider_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      service_requests: {
        Row: {
          id: string;
          client_id: string;
          provider_id: string | null;
          service_id: string;
          status: string;
          address: string;
          latitude: number | null;
          longitude: number | null;
          scheduled_date: string;
          scheduled_time: string;
          variables: Json | null;
          estimated_price: number;
          final_price: number | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          provider_id?: string | null;
          service_id: string;
          status?: string;
          address: string;
          latitude?: number | null;
          longitude?: number | null;
          scheduled_date: string;
          scheduled_time: string;
          variables?: Json | null;
          estimated_price: number;
          final_price?: number | null;
          notes?: string | null;
        };
        Update: {
          id?: string;
          client_id?: string;
          provider_id?: string | null;
          service_id?: string;
          status?: string;
          address?: string;
          latitude?: number | null;
          longitude?: number | null;
          scheduled_date?: string;
          scheduled_time?: string;
          variables?: Json | null;
          estimated_price?: number;
          final_price?: number | null;
          notes?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "service_requests_client_id_fkey";
            columns: ["client_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "service_requests_provider_id_fkey";
            columns: ["provider_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "service_requests_service_id_fkey";
            columns: ["service_id"];
            isOneToOne: false;
            referencedRelation: "services";
            referencedColumns: ["id"];
          },
        ];
      };
      payments: {
        Row: {
          id: string;
          request_id: string;
          stripe_payment_intent_id: string;
          amount: number;
          platform_fee: number;
          provider_amount: number;
          currency: string;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          request_id: string;
          stripe_payment_intent_id: string;
          amount: number;
          platform_fee: number;
          provider_amount: number;
          currency?: string;
          status?: string;
        };
        Update: {
          id?: string;
          request_id?: string;
          stripe_payment_intent_id?: string;
          amount?: number;
          platform_fee?: number;
          provider_amount?: number;
          currency?: string;
          status?: string;
        };
        Relationships: [
          {
            foreignKeyName: "payments_request_id_fkey";
            columns: ["request_id"];
            isOneToOne: false;
            referencedRelation: "service_requests";
            referencedColumns: ["id"];
          },
        ];
      };
      chat_rooms: {
        Row: {
          id: string;
          request_id: string;
          client_id: string;
          provider_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          request_id: string;
          client_id: string;
          provider_id: string;
        };
        Update: {
          id?: string;
          request_id?: string;
          client_id?: string;
          provider_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "chat_rooms_request_id_fkey";
            columns: ["request_id"];
            isOneToOne: true;
            referencedRelation: "service_requests";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "chat_rooms_client_id_fkey";
            columns: ["client_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "chat_rooms_provider_id_fkey";
            columns: ["provider_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      chat_messages: {
        Row: {
          id: string;
          room_id: string;
          sender_id: string;
          content: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          room_id: string;
          sender_id: string;
          content: string;
        };
        Update: {
          id?: string;
          room_id?: string;
          sender_id?: string;
          content?: string;
        };
        Relationships: [
          {
            foreignKeyName: "chat_messages_room_id_fkey";
            columns: ["room_id"];
            isOneToOne: false;
            referencedRelation: "chat_rooms";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "chat_messages_sender_id_fkey";
            columns: ["sender_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      reviews: {
        Row: {
          id: string;
          request_id: string;
          reviewer_id: string;
          reviewee_id: string;
          rating: number;
          comment: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          request_id: string;
          reviewer_id: string;
          reviewee_id: string;
          rating: number;
          comment?: string | null;
        };
        Update: {
          id?: string;
          request_id?: string;
          reviewer_id?: string;
          reviewee_id?: string;
          rating?: number;
          comment?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "reviews_request_id_fkey";
            columns: ["request_id"];
            isOneToOne: false;
            referencedRelation: "service_requests";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reviews_reviewer_id_fkey";
            columns: ["reviewer_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reviews_reviewee_id_fkey";
            columns: ["reviewee_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      platform_config: {
        Row: {
          id: string;
          key: string;
          value: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          key: string;
          value: string;
        };
        Update: {
          id?: string;
          key?: string;
          value?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      user_role: "client" | "provider";
      request_status:
        | "pending"
        | "waiting_acceptance"
        | "accepted"
        | "in_progress"
        | "completed"
        | "cancelled";
      payment_status: "authorized" | "captured" | "cancelled" | "refunded";
      variable_type: "number" | "select" | "boolean";
    };
    CompositeTypes: Record<string, never>;
  };
}
