import { StyleSheet } from "react-native";
import { COLORS, SPACING, FONT_SIZE, BORDER_RADIUS } from "@/lib/constants";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.background,
    },
    content: {
        flex: 1,
        alignItems: "center",
        padding: SPACING.lg,
    },
    searchIconContainer: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: COLORS.surface,
        alignItems: "center",
        justifyContent: "center",
        marginVertical: SPACING.lg,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 10,
        elevation: 4,
    },
    avatar: {
        width: 60,
        height: 60,
        borderRadius: 30,
    },
    searchingTitle: {
        fontSize: FONT_SIZE.lg,
        fontWeight: "700",
        color: COLORS.primary,
        textAlign: "center",
        marginBottom: 8,
    },
    searchingSubtitle: {
        fontSize: FONT_SIZE.lg,
        fontWeight: "700",
        color: COLORS.text,
        textAlign: "center",
        paddingHorizontal: SPACING.lg,
        lineHeight: 24,
        marginBottom: 8,
    },
    timerBadge: {
        backgroundColor: COLORS.primaryLight,
        paddingHorizontal: 12,
        paddingVertical: 4,
        borderRadius: 20,
        flexDirection: "row",
        alignItems: "center",
        marginBottom: SPACING.md,
    },
    timerLabel: {
        fontSize: 10,
        color: COLORS.textSecondary,
        marginRight: 8,
    },
    timerValue: {
        fontSize: 10,
        color: COLORS.primary,
        fontWeight: "700",
    },
    disclaimerBar: {
        fontSize: 10,
        color: COLORS.textTertiary,
        textAlign: "center",
        paddingHorizontal: SPACING.xl,
        marginBottom: SPACING.xl,
    },
    requestCard: {
        backgroundColor: COLORS.surface,
        borderRadius: BORDER_RADIUS.lg,
        padding: SPACING.lg,
        width: "100%",
        marginBottom: SPACING.lg,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 2,
    },
    requestTitle: {
        fontSize: FONT_SIZE.md,
        fontWeight: "700",
        color: COLORS.text,
        marginBottom: SPACING.md,
    },
    requestItem: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: SPACING.sm,
    },
    requestText: {
        fontSize: FONT_SIZE.sm,
        color: COLORS.textSecondary,
        marginLeft: SPACING.sm,
        flex: 1,
    },
    footer: {
        padding: SPACING.lg,
        backgroundColor: COLORS.surface,
        borderTopWidth: 1,
        borderTopColor: COLORS.border,
    },
    primaryButton: {
        backgroundColor: COLORS.success,
        borderRadius: BORDER_RADIUS.md,
        padding: SPACING.lg,
        alignItems: "center",
        marginBottom: SPACING.md,
    },
    primaryButtonText: {
        color: "white",
        fontSize: FONT_SIZE.md,
        fontWeight: "700",
    },
    secondaryButton: {
        paddingVertical: SPACING.md,
        alignItems: "center",
        borderWidth: 1,
        borderColor: COLORS.error,
        borderRadius: BORDER_RADIUS.md,
    },
    secondaryButtonText: {
        color: COLORS.error,
        fontSize: FONT_SIZE.md,
        fontWeight: "600",
    },
    bottomMessage: {
        fontSize: 10,
        color: COLORS.textTertiary,
        textAlign: "center",
        marginTop: SPACING.md,
    },
});
